### ISSUE TITLE
UCI format for engine use

### ISSUE THREAD

**Issue by ASilver** [saikrishna-1996/deep_pepper_chess#3]
For the resulting engine to be more easily used, would it be possible to provide code that can be compiled into a binary that can abides by the UCI protocol? This protocol is widely used by all the major interfaces such as Arena, ChessBase, Fritz, and many many more.

**Comment by saikrishna-1996** [comment]
Right now, we are focusing on improving the performance of the engine with hyper parameter tuning. Feel free to contribute :+1:
