### ISSUE TITLE
Provide instructions on pretraining 

### ISSUE THREAD

**Issue by dkappe** [saikrishna-1996/deep_pepper_chess#4]
There are many pretraining python files, but no instructions on which to prefer. How to take a large database of a few million pgn games and pretrain?

**Comment by saikrishna-1996** [comment]
game/pretrain.py works. 
Replace this line https://github.com/saikrishna-1996/deep_pepper_chess/blob/master/game/pretrain.py#L19 with the path to your .pgn folder. Excited to see how it works on MegaDatabase ;)
